//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlossarySystem
    {
        public int Id { get; set; }
        public string WordGlossary { get; set; }
        public int WordValue { get; set; }
        public int SystemCollectionId { get; set; }
    
        public virtual SystemCollection SystemCollection { get; set; }
    }
}
