//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDemand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupDemand()
        {
            this.TypeDemands = new HashSet<TypeDemand>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int SystemCollectionId { get; set; }
    
        public virtual SystemCollection SystemCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeDemand> TypeDemands { get; set; }
    }
}
