//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelQAContainer : DbContext
    {
        public ModelQAContainer()
            : base("name=ModelQAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<SystemCollection> SystemCollections { get; set; }
        public virtual DbSet<UserSystems> UserSystems { get; set; }
        public virtual DbSet<UserQuestions> UserQuestions { get; set; }
        public virtual DbSet<GroupDemand> GroupDemands { get; set; }
        public virtual DbSet<TypeDemand> TypeDemands { get; set; }
        public virtual DbSet<DemandDescription> DemandDescriptions { get; set; }
        public virtual DbSet<GlossarySystem> GlossarySystems { get; set; }
    }
}
