//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSystems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSystems()
        {
            this.UserQuestions = new HashSet<UserQuestions>();
        }
    
        public int Id { get; set; }
        public int SystemCollectionId { get; set; }
        public int UserDataId { get; set; }
    
        public virtual SystemCollection SystemCollection { get; set; }
        public virtual UserData UserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuestions> UserQuestions { get; set; }
    }
}
